title: Jon Schulman
tagline: Parrot rescuer, DeLorean driver, product manager

author:
  name: Jon
  url: https://twitter.com/jonnyborbs

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

paginate: 5

tags_path: /tags/
categories_path: /categories/
