title: jonnyborbs
tagline: reactor networks

author:
  name: Jon
  url: https://twitter.com/jonnyborbs

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

paginate: 3

tags_path: /tags/
categories_path: /categories/
